package dao;

import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.proxy.annotation.Pre;
import util.DBManager;
import util.IOManager;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class Account {
    private long account_id = 0;
    private long account_number;
    private String type;
    private double interest_rate;
    private double min_balance;
    private Timestamp created;

    private ArrayList<Person> owners;

    /**
     * Constructor for creating new Account objects to save in db
     * @param type the type of account to be created
     */
    public Account(String type) {
        this.type = type;
        this.owners = new ArrayList<Person>();
    }

    /**
     * Constructor for Account objects using data from db
     * @param account_id
     * @param account_number
     * @param type
     * @param interest_rate
     * @param min_balance
     * @param created
     */
    public Account(long account_id, long account_number, String type, double interest_rate, double min_balance, Timestamp created)
    {
        this.account_id = account_id;
        this.account_number = account_number;
        this.type = type;
        this.interest_rate = interest_rate;
        this.min_balance = min_balance;
        this.created = created;
    }

    /**
     * Save a newly created account object to the database
     * Cannot update values if the account has already been inserted
     * Account ID and Account Number are both generated by the database upon insert
     * @return boolean whether the database insertion was successful
     */
    public boolean save() {
        Connection conn = DBManager.getConnection();

        if (this.account_id == 0) {
            String query = "insert into account" +
                    "(type, interest_rate, min_balance)" +
                    "values (?, ?, ?) returning account_id, account_number into ?, ?";
            try (
                    OraclePreparedStatement ps = (OraclePreparedStatement)conn.prepareStatement(query);
            ) {
                conn.setAutoCommit(false);
                ps.setString(1, this.type);
                ps.setDouble(2, this.interest_rate);
                ps.setDouble(3, this.min_balance);
                ps.registerReturnParameter(4, Types.NUMERIC);
                ps.registerReturnParameter(5, Types.NUMERIC);

                if (ps.executeUpdate() == 0) {
                    DBManager.rollbackAndResetAutoCommit();
                    return false;
                }

                ResultSet rs = ps.getReturnResultSet();

                if (rs != null && rs.next()) {
                    this.account_id = rs.getLong(1);
                    this.account_number = rs.getLong(2);
                }
                else
                {
                    throw new SQLException("Row possibly not inserted or something");
                }

                for (Person person : this.owners) {
                    PreparedStatement join = conn.prepareStatement("insert into person_account " +
                            "(person_id, account_id) values (?, ?)");

                    join.setLong(1, person.getPersonId());
                    join.setLong(2, this.account_id);

                    join.executeUpdate();
                }

                conn.commit();
                conn.setAutoCommit(true);
            } catch (SQLException e) {
                DBManager.rollbackAndResetAutoCommit();
                return false;
            }
            return true;
        }
        return false;
    }

    /**
     * Initialize Account object by searching the database using an account_id
     * @param account_id
     * @return populated Account object or null if failed
     */
    public static Account fromAccountId(long account_id)
    {
        Connection conn = DBManager.getConnection();
        Account account = null;

        try {
            PreparedStatement ps = conn.prepareStatement(
                    "SELECT a.* " +
                            "FROM account a " +
                            "WHERE a.account_id = ?");

            ps.setLong(1, account_id);

            ResultSet result = ps.executeQuery();

            if (result != null && result.next()) {
                account = new Account(
                        result.getLong("account_id"),
                        result.getLong("account_number"),
                        result.getString("type"),
                        result.getDouble("interest_rate"),
                        result.getDouble("min_balance"),
                        result.getTimestamp("created")
                );
            }
            else {
                return null;
            }
        }
        catch (SQLException e)
        {
            return null;
        }

        return account;
    }

    /**
     * Initialize Account object by searching the database using an account number
     * @param account_number
     * @return populated Account object or null if failed
     */
    public static Account fromNumber(long account_number)
    {
        Connection conn = DBManager.getConnection();
        Account account = null;

        try {
            PreparedStatement ps = conn.prepareStatement(
                    "SELECT a.* " +
                            "FROM account a " +
                            "WHERE a.account_number = ?");

            ps.setLong(1, account_number);

            ResultSet result = ps.executeQuery();

            if (result != null && result.next()) {
                account = new Account(
                        result.getLong("account_id"),
                        result.getLong("account_number"),
                        result.getString("type"),
                        result.getDouble("interest_rate"),
                        result.getDouble("min_balance"),
                        result.getTimestamp("created")
                );
            }
            else {
                return null;
            }
        }
        catch (SQLException e)
        {
            return null;
        }

        return account;
    }

    /**
     * Initialize Account object by searching the database using a debit card number
     * @param card_number
     * @return populated Account object or null if failed
     */
    public static Account fromDebitCard(long card_number)
    {
        Connection conn = DBManager.getConnection();
        Account account = null;

        try {
            PreparedStatement ps = conn.prepareStatement(
                    "SELECT a.* " +
                            "FROM card c " +
                            "INNER JOIN card_debit cd " +
                            "ON c.card_id = cd.card_id " +
                            "INNER JOIN account a " +
                            "ON cd.account_id = a.account_id " +
                            "WHERE c.card_number = ? " +
                            "AND c.status = 'active'");

            ps.setLong(1, card_number);

            ResultSet result = ps.executeQuery();

            if (result != null && result.next()) {
                account = new Account(
                        result.getLong("account_id"),
                        result.getLong("account_number"),
                        result.getString("type"),
                        result.getDouble("interest_rate"),
                        result.getDouble("min_balance"),
                        result.getTimestamp("created"));
            }
            else {
                return null;
            }
        }
        catch (SQLException e)
        {
            return null;
        }

        return account;
    }

    /**
     * Get all accounts associated with a specific person via their email address
     * @param email
     * @return list of accounts associated with the email address entered, empty if failed
     */
    public static List<Account> getAllFromEmail(String email)
    {
        Connection conn = DBManager.getConnection();
        List<Account> account_list = new ArrayList<Account>();

        try {
            PreparedStatement ps = conn.prepareStatement(
                    "SELECT a.* " +
                            "FROM person p " +
                            "INNER JOIN person_account pa " +
                            "ON p.person_id = pa.person_id " +
                            "INNER JOIN account a " +
                            "ON pa.account_id = a.account_id " +
                            "WHERE p.email = ? " +
                            "ORDER BY a.created ASC");

            ps.setString(1, email);

            ResultSet result = ps.executeQuery();

            if (result != null && result.next()) {
                do {
                    account_list.add(new Account(
                            result.getLong("account_id"),
                            result.getLong("account_number"),
                            result.getString("type"),
                            result.getDouble("interest_rate"),
                            result.getDouble("min_balance"),
                            result.getTimestamp("created")));
                }
                while (result.next());
            }
        }
        catch (SQLException e)
        {
            return new ArrayList<Account>();
        }

        return account_list;
    }

    /**
     * Get the current balance of the account by taking advantage of a view in the db
     * @return the current balance or 0 if there are any errors.
     */
    public double getBalance()
    {
        if (this.account_id == 0)
        {
            return 0;
        }

        Connection conn = DBManager.getConnection();

        try {
            PreparedStatement ps = conn.prepareStatement(
                    "SELECT ab.balance " +
                            "FROM account_balance ab " +
                            "WHERE ab.account_id = ?");

            ps.setLong(1, this.account_id);

            ResultSet result = ps.executeQuery();

            if (result != null && result.next()) {
                return result.getDouble("balance");
            }
            else
            {
                return 0;
            }
        }
        catch (SQLException e)
        {
            return 0;
        }
    }

    /**
     * Check if a specific person is an owner of the account
     * @param person a person object with a person_id
     * @return whether the person is an owner of the account
     */
    public boolean hasOwner(Person person)
    {
        if (person == null || person.getPersonId() == 0)
        {
            return false;
        }

        Connection conn = DBManager.getConnection();
        try {
            PreparedStatement ps = conn.prepareStatement(
                    "SELECT count(pa.person_id) as person_count " +
                            "FROM person_account pa " +
                            "WHERE pa.account_id = ? " +
                            "AND pa.person_id = ?");

            ps.setLong(1, this.account_id);
            ps.setLong(2, person.getPersonId());

            ResultSet result = ps.executeQuery();

            if (result == null || !result.next() || result.getLong("person_count") == 0) {
                return false;
            }
        }
        catch (SQLException e)
        {
            return false;
        }

        return true;
    }

    /**
     * Create deposit transaction into this account
     * @param amount
     * @param person
     * @param branch
     * @return whether deposit was successful
     */
    public boolean deposit(double amount, Person person, Branch branch)
    {
        if (this.account_id == 0)
        {
            return false;
        }

        Transaction_Transfer deposit = Transaction_Transfer.getDeposit(amount, this, person, branch);

        if (deposit != null && deposit.save())
        {
            return true;
        }

        return false;
    }

    /**
     * Create deposit transaction from this account
     * @param amount
     * @param person
     * @param branch
     * @return whether withdrawal was successful
     */
    public boolean withdrawal(double amount, Person person, Branch branch)
    {
        if (this.account_id == 0)
        {
            return false;
        }

        Transaction_Transfer withdrawal = Transaction_Transfer.getWithdrawal(amount, this, person, branch);

        if (withdrawal != null && withdrawal.save())
        {
            return true;
        }

        return false;
    }

    /**
     * @return string representing the account of the form "SAVINGS - *********1234 balance: $123.45"
     */
    public String toString()
    {
        return this.type.toUpperCase() + " - *********" + this.getLastFour() + " balance: " + IOManager.formatCurrency(this.getBalance());
    }

    // Getters and Setters
    public long getAccountId() {
        return account_id;
    }

    public long getAccountNumber() {
        return account_number;
    }

    public long getLastFour()
    {
        return account_number % 10000;
    }

    public String getType() {
        return type;
    }

    public double getInterestRate() {
        return interest_rate;
    }

    public void setInterestRate(double interest_rate) {
        this.interest_rate = interest_rate;
    }

    public double getMinBalance() {
        return min_balance;
    }

    public void setMinBalance(double min_balance) {
        this.min_balance = min_balance;
    }

    public Timestamp getCreated() {
        return created;
    }

    public void addPerson(Person person)
    {
        this.owners.add(person);
    }
}
